hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "439286e6444ce4d19e902d16f6350b3a203af04a23437d33034795b35be6ce0f"

[[files]]
file = "config/Veinminer/blocks.json"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/Veinminer/settings.json"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/carpet/default_carpet.conf"
hash = "dd95721929538c1db8a851cbaf1fe1b8b2327e5e03f382957814b2c5dc05bbf7"

[[files]]
file = "config/create-client.toml"
hash = "3328bab9772dfc891557b435dd3cf661536ed3516f347384407a7aad27f54b86"

[[files]]
file = "config/create-common.toml"
hash = "36a4d9f5da68f6801b83ce0c4a1a8805fbeffb0dd997f2d405465d7774522296"

[[files]]
file = "config/create-server.toml"
hash = "7e10a3299dd879660d2c1370b86e6dfba3d83129d88f369d4f0b29aaafcd59cb"

[[files]]
file = "config/createaddition-common-1.toml.bak"
hash = "2b16428cdce3468e1982d026be2b5c3e9b9a04e5d911fe4335bf6130819bf129"

[[files]]
file = "config/createaddition-common.toml"
hash = "3603ad8a2e867722baac0e7949891e51847b770bab8a5bd47e894c9466b96472"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "6875bc2aaff1889d158bbcace861ae9e620e584c181e5e67343fdccea9e3feb1"

[[files]]
file = "config/fabrictailor.json"
hash = "327559103587c2c6844f91ef12110e6070262e172e269c62a7aac1f014e3c3ab"

[[files]]
file = "config/flywheel.json"
hash = "8d5385ce9f9af3458c877db2ee7bf73230202c24870dece6b7e97e344fb8dfc1"

[[files]]
file = "config/forgeconfigapiport.toml"
hash = "ac070ed460bf105be08b98392544e52093232aaf2cee8e3db826bb709ed535cd"

[[files]]
file = "config/immediatelyfast.json"
hash = "f2b7f219198f0a911d04b09f545f2c1256e8d114951443924878dc10963e16aa"

[[files]]
file = "config/indium-renderer.properties"
hash = "aa698cd15b0c702a50aa2a27a478e6523a6bbaa7f3a9778bd7beaed7a7285e69"

[[files]]
file = "config/iris.properties"
hash = "e1420588fb2f4ae6797017fb6f7f4efc99eaa13d0c3afef47e83ca2924408fd5"

[[files]]
file = "config/modmenu.json"
hash = "748cb550ed31f0d7f2a8faf26cd0c659826ae10cfabc4a89eee7d32eed98f157"

[[files]]
file = "config/ponder-client.toml"
hash = "4b29b3cbcf0a5a2ffdf0d74a252db2f65a3af4164629592772cfb53a5e091df6"

[[files]]
file = "config/railways-client.toml"
hash = "68a8691f7e297631df3d99b1e5025886f3d8f8bf8bbfbe61f93ebec2d2c28d57"

[[files]]
file = "config/railways-common-1.toml.bak"
hash = "7f9c9e31ac8256ca2f258583df262dbc7d6f68f2a03043d5c99a4ae5a7396ce9"

[[files]]
file = "config/railways-common.toml"
hash = "1f660c8bd0c374799862392ef7a56253544f5adaf653e59386cd1eb34f94fa2f"

[[files]]
file = "config/railways-server.toml"
hash = "463c5e5605677d889746ba9b35b29ecf46e87573ce501c0fb12519e001c8a9fc"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "4b4de2780d50ac3ec6d6a707e5d72be21687a12f7552d64eb2c5013b11950c1c"

[[files]]
file = "config/sodium-mixins.properties"
hash = "8939df3a10627cf3b9a3cc0e2824337923e9a26d11e60f5a1f7c0cfbd171a574"

[[files]]
file = "config/sodium-options.json"
hash = "e170cafd722ce62aa061d6770af08274391dd17064f58e82e2ff84af2b1f95ac"

[[files]]
file = "data/fabricDefaultResourcePacks.dat"
hash = "56dcdc36f4d3fe993c688cd6d60c2ef0d83480a63305425e068d171f8fcda7db"

[[files]]
file = "icon.png"
hash = "247dfe5bf4e6c33acadbc90e91a28d74ea25f0c1471264de2ddc0ca1a6ee7bbd"

[[files]]
file = "irisUpdateInfo.json"
hash = "2ae3d55c9841b7dd3a610bbdfcbba81f40003f6ef942942fbf1aef100fbb73e7"

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "3b87f6113f1304c82ad4efedbf049c239548be6e642acd63d82020504f5b0953"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "f912004cc3c195008c32edf5ad4108639eb36530221886034cdd03b7916a220a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "964a56ef500d320801315eb45687e51e9352f03615506469979875d2fed41760"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8e0ab4317f114231fa313af5fc1b5fadf0e8096d712bdc1fd7359077a003d389"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "25ccb0dd97330715a5a5dd4ab2a9820811085116ee7b6fa8d38e6b0d453321eb"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f644c401c3ef437f661564171abc8be8f13ad71cb67461734ab402d2ebe7cc47"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "3159f65be74fdf8c382f2079d9db965972c8612e661f126be522ae37a73c34f8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "213860e0c0161f60fba897f526d92ca703208dd26b636e6eaadb2c715d8a2f58"
metafile = true

[[files]]
file = "options.txt"
hash = "6d1c15a4f58affedbb8da26245ec9f3efab83a9c9853fc2dbffb2ec60dbddf46"

[[files]]
file = "pack"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "servers.dat"
hash = "4a923ede12ac1bab32325d51ca15c3d3ede54be73b2d62b46b8491677b7aaaf6"

[[files]]
file = "shaderpacks/.index/complementary-reimagined.pw.toml"
hash = "e935a7ea1bc6233b13a6d0c6a1ab6e6ac6fb6df4cfcb52e5157cb6366200b5eb"
metafile = true

[[files]]
file = "usercache.json"
hash = "30719502b15467b8e99d9a091259109833cd4f6e001d7cf836a4cb3e9fb87e3b"

[[files]]
file = "usernamecache.json"
hash = "bf350f30592db358103a8272fd926eafcc330064030433b3f6b1035e58f7dc2b"
