name = "Create DenDan"
author = "slyw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4143081c1fd8071a5089ca9cdccca3018521a87a8e889c4a5ca1060cdf9797b0"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
